"""Centralised bilingual copy for the ClaimTrace Streamlit interface."""


UI_TEXT = {
    "zh": {
        "page_subtitle": "面向中文电商广告宣称的证据导向风险初筛工作台",
        "page_eyebrow": "中文电商文案 · 发布前风险初筛",
        "page_headline": "每条文案，都应有一条可核对的证据轨迹。",
        "english_subtitle": "Evidence-grounded screening for Chinese e-commerce advertising claims",
        "brand_promise": "先核对规则与历史案例，再给出风险提示；检索证据不足时，系统停止自动判断并提示需要人工复核。",
        "preliminary_status": "初步筛查",
        "hero_visual_alt": "文案经过案例检索后进入风险提示或人工复核提示的证据轨迹示意图",
        "visual_title": "Evidence trail / 证据轨迹",
        "visual_input": "输入文案",
        "visual_evidence": "检索证据",
        "visual_review": "判断或转人工",
        "trust_evidence": "证据优先",
        "trust_trace": "路径可追溯",
        "trust_human": "人工最终确认",
        "language_label": "界面语言",
        "boundary_title": "发布前初筛，而非自动审批",
        "boundary_text": "本工具仅用于初步风险筛查，不构成法律意见，也不会自动批准商品文案。可筛查普通商品文案中的治愈、疾病预防等危险宣传，不提供医疗、金融或其他专业领域的决策与合规批准。低风险不等于法律批准，正式发布仍需人工确认。系统仅提示需要人工复核，没有自动派发工单或指定接收人的功能，请自行交由人工检查。",
        "start_review": "开始审查",
        "start_review_help": "一次输入一条中文商品文案，查看规则、案例与风险提示。",
        "claim_label": "待审查的中文商品文案",
        "claim_placeholder": "例如：本产品是全网销量第一的护肤品。",
        "try_example": "使用示例",
        "example_high": "治疗保证",
        "example_evidence": "销量宣称",
        "example_low": "商品规格",
        "example_high_text": "这款普通靠垫保证彻底治愈腰椎间盘突出。",
        "example_evidence_text": "本店手机壳销量全平台第一。",
        "example_low_text": "这款笔记本可选择横线页或空白页。",
        "clear": "清空文案",
        "assess_claim": "开始风险审查",
        "empty_input": "请先输入一条中文商品文案；系统尚未运行。",
        "assessing": "正在检索案例并准备风险评估……",
        "workflow_title": "审核路径",
        "workflow_help": "主证据链直接展示，规则基线保持独立。",
        "workflow_input": "输入文案",
        "workflow_input_help": "一次提交一条中文商品文案；切换界面语言不会清空输入。",
        "workflow_rule": "独立规则基线",
        "workflow_rule_help": "识别已配置的高风险词与需要证明的宣称。",
        "workflow_retrieval": "案例检索",
        "workflow_retrieval_help": "从 30 条案例记录中返回文本最相近的 3 条。",
        "workflow_threshold": "证据阈值",
        "workflow_threshold_help": "以暂定阈值 0.30 判断是否有足够检索证据。",
        "workflow_decision": "模型初筛或人工复核提示",
        "workflow_decision_help": "达到阈值时至多调用模型一次，否则提示需要人工复核，请自行交由人工检查。",
        "baseline_independent": "规则结果是独立基线，不直接决定最终风险卡。",
        "reference_rules_title": "项目参考标签",
        "reference_rules_help": "三类人工参考标签用于项目评估，不是监管机关给出的官方标签。",
        "empty_state_label": "等待输入",
        "empty_state_title": "结果会沿证据轨迹在这里展开",
        "empty_input_step": "保留用户原始文案，供后续核对。",
        "empty_evidence_step": "检索相似案例，并检查暂定阈值。",
        "empty_review_step": "给出风险提示；证据不足时请交由人工复核。",
        "empty_state_note": "相似度只表示文本接近程度，不是违法概率。",
        "result_ready": "本次初筛已形成",
        "result_ready_help": "下方将展开判断理由、案例来源与技术信息。",
        "principle_score_title": "相似度不是风险概率",
        "principle_score_body": "它只表示输入与案例文本的接近程度。",
        "principle_source_title": "引用必须支持结论",
        "principle_source_body": "历史案例只能提供类比依据，不能证明当前事实。",
        "principle_human_title": "发布决定由人负责",
        "principle_human_body": "任何系统输出都不构成自动批准。",
        "results_title": "审查结果",
        "results_help": "先看结论和行动，再沿证据链核对形成过程。",
        "baseline_result": "规则初筛结果",
        "independent_baseline": "独立基线，仅作对照",
        "best_similarity": "最佳案例文本相似度",
        "text_similarity_only": "仅表示文本相似程度",
        "final_risk": "系统初筛风险",
        "human_review": "是否需要转人工",
        "review_required": "系统未给出确定判断",
        "human_confirmation": "发布前仍需人工确认",
        "human_confirmation_required": "发布前人工确认",
        "automatic_judgment": "系统判断状态",
        "auto_completed": "已完成",
        "auto_declined": "已拒绝判断",
        "yes": "是",
        "no": "否",
        "not_available": "不可用",
        "assessment_interrupted": "系统未完成案例检索",
        "assessment_incomplete": "评估未完成",
        "no_automatic_conclusion": "不输出自动批准或风险结论",
        "tab_overview": "结果概览",
        "tab_cases": "相似案例",
        "tab_rules": "规则详情",
        "tab_evidence": "证据与规则",
        "tab_technical": "技术信息",
        "system_error": "系统未能完成本次评估，需要人工复核；请自行交由人工检查。",
        "system_error_action": "请勿据此发布文案；可稍后重试或交由人工检查。",
        "risk_level": "初筛风险等级",
        "highlighted_claim": "重点文案",
        "system_explanation": "系统说明",
        "model_original_reason": "模型原始解释",
        "next_action": "建议的下一步",
        "decision_label": "本次初筛结论",
        "evidence_reason": "发现了什么",
        "evidence_action": "接下来做什么",
        "why_this_result": "判断理由",
        "what_to_do_next": "建议行动",
        "rule_findings": "规则命中",
        "case_sources": "相似案例与来源",
        "model_original_action": "模型原始建议",
        "confidence": "模型自报置信值",
        "confidence_note": "该值不是违法概率或监管处罚概率。",
        "abstained": "是否拒绝自动判断",
        "supporting_source": "引用来源",
        "open_cited_source": "打开引用的官方来源",
        "none": "无",
        "fixed_human_notice": "正式发布决定始终由人工负责。",
        "trace_title": "ClaimTrace 证据链",
        "trace_help": "规则基线只作独立对照；主链展示案例、阈值与初筛判断或人工复核提示。",
        "trace_baseline": "独立对照",
        "trace_cases": "案例检索",
        "trace_cases_detail": "最佳文本相似度 {score}，不是风险概率。",
        "trace_threshold": "阈值判断",
        "trace_threshold_pass": "{score} ≥ 暂定阈值 {threshold}，进入模型评估。",
        "trace_threshold_fail": "{score} < 暂定阈值 {threshold}，证据不足。",
        "trace_decision": "初筛与复核提示",
        "trace_model": "模型至多调用一次，输出风险提示。",
        "trace_human": "系统拒绝确定判断，需要人工复核；请交由人工检查。",
        "trace_error": "流程未完成，需要人工复核；没有自动派发，请自行交由人工检查。",
        "trace_unavailable": "本次没有可报告的数据。",
        "similarity_disclaimer": "以下数值仅为文本相似度。历史案例相似不等于当前商品、商家或事实相同。",
        "language_content_note": "模型解释与外部案例标题可能保留原始语言，页面不会将其描述为已完整翻译。",
        "case_rank": "相似案例 {index}",
        "case_id": "案例编号",
        "text_similarity": "文本相似度",
        "risk_type": "案例记录的风险类型",
        "case_summary": "查看案例摘要",
        "official_source": "打开官方来源",
        "no_cases_available": "本次评估没有可显示的案例结果。",
        "matched_fragment": "命中的原文片段",
        "rule_explanation": "对应规则说明",
        "no_rule_match": "有限规则库未命中已配置的表达。",
        "no_rule_match_help": "这不代表文案真实、合法或获得批准，仍需结合商品事实和证明材料人工确认。",
        "rule_scope_note": "规则列表不是完整法律规则库，未命中不等于批准。",
        "technical_expander": "展开本次请求的技术信息",
        "threshold": "暂定阈值",
        "llm_called": "是否调用模型",
        "model": "模型名称",
        "not_called": "未调用",
        "threshold_note": "0.30 为暂定检索阈值，尚未经过充分校准。",
        "single_request_usage": "服务返回的单次请求用量",
        "prompt_tokens": "输入 Token",
        "completion_tokens": "输出 Token",
        "request_total_tokens": "本次总 Token",
        "request_cost": "本次请求成本",
        "usage_not_reported": "服务未返回本次请求的 Token 或成本数据。",
        "model_error_type": "模型或流程错误类型",
        "no_usage_on_error": "评估未完成，因此没有可报告的模型用量。",
        "technical_boundary": "技术值用于解释本次请求，不代表违法概率、监管处罚概率或法律结论。",
        "final_responsibility": "低风险不等于法律批准；正式发布仍需人工确认。",
        "sidebar_title": "审查工作台",
        "sidebar_status": "原型系统 · 单条文案初筛",
        "sidebar_guide": "状态图例",
        "sidebar_limits": "关键边界",
        "rule_high_title": "高风险",
        "rule_high_body": "治愈、根治、包治等治疗保证，以及最佳、最高级、国家级等高风险绝对化表达。",
        "rule_evidence_title": "需要证据",
        "rule_evidence_body": "销量与排名、价格与套餐、材质与来源、证书、性能、效果、改善或提升等宣称。",
        "rule_low_title": "较低风险",
        "rule_low_body": "仅表示有限规则和案例库中未识别出明显风险；不代表真实、合法或获批。",
        "rule_insufficient_title": "证据不足",
        "rule_insufficient_body": "不是参考标签；表示系统拒绝在检索证据不足时给出确定判断，需要人工复核。",
        "limit_rules": "规则列表不是完整法律规则库。",
        "limit_cases": "历史案例相似不等于当前事实相同。",
        "limit_citation": "引用必须真正支持当前结论。",
        "limit_threshold": "当前阈值 0.30 只是暂定值。",
        "limit_human": "正式发布需要人工确认。",
        "rule_medical": "该片段包含疾病治疗或治愈保证。",
        "rule_superlative": "该片段包含高风险绝对化或最高级表达。",
        "rule_sales": "销量或排名宣称需要可核验的交易记录支持。",
        "rule_price": "价格或套餐宣称需要与实际优惠和条件核对。",
        "rule_effect": "产品效果或改善宣称需要可靠证明材料支持。",
        "retrieval_below_threshold": "检索证据低于暂定阈值，系统未给出确定标签。",
        "send_human_review": "发布前请将该文案交由人工复核。",
    },
    "en": {
        "page_subtitle": "An evidence-grounded review workspace for Chinese e-commerce advertising claims",
        "page_eyebrow": "Chinese e-commerce copy · pre-publication risk screening",
        "page_headline": "Give every claim a traceable evidence trail.",
        "english_subtitle": "Evidence-grounded screening for Chinese e-commerce advertising claims",
        "brand_promise": "Check rules and historical cases before issuing a risk signal. When retrieval support is insufficient, the system stops short of a definite judgement and indicates that human review is needed.",
        "preliminary_status": "Preliminary screening",
        "hero_visual_alt": "Evidence-trail diagram showing a claim moving through case retrieval to a risk signal or a human-review notice",
        "visual_title": "Evidence trail",
        "visual_input": "Claim input",
        "visual_evidence": "Evidence retrieval",
        "visual_review": "Signal or human review",
        "trust_evidence": "Evidence first",
        "trust_trace": "Traceable path",
        "trust_human": "Human confirmation",
        "language_label": "Interface language",
        "boundary_title": "Pre-publication screening, not automatic approval",
        "boundary_text": "This tool is for preliminary risk screening only. It does not provide legal advice or automatically approve product copy. It can screen dangerous cure or disease-prevention claims in advertising for ordinary goods, but does not provide medical, financial or other professional decisions or compliance approval. Low risk is not legal approval; final publication still requires human confirmation. Human-review notices do not dispatch a task or assign a recipient. Please arrange human review yourself.",
        "start_review": "Start a review",
        "start_review_help": "Enter one Chinese product claim to inspect rules, cases and risk signals.",
        "claim_label": "Chinese product claim to review",
        "claim_placeholder": "For example: 本产品是全网销量第一的护肤品。",
        "try_example": "Try an example",
        "example_high": "Treatment guarantee",
        "example_evidence": "Sales claim",
        "example_low": "Product specification",
        "example_high_text": "这款普通靠垫保证彻底治愈腰椎间盘突出。",
        "example_evidence_text": "本店手机壳销量全平台第一。",
        "example_low_text": "这款笔记本可选择横线页或空白页。",
        "clear": "Clear claim",
        "assess_claim": "Start risk review",
        "empty_input": "Enter a Chinese product claim first; the system has not run.",
        "assessing": "Retrieving cases and preparing the assessment…",
        "workflow_title": "Review path",
        "workflow_help": "The evidence chain is shown directly; the rule baseline stays independent.",
        "workflow_input": "Enter a claim",
        "workflow_input_help": "Submit one Chinese product claim at a time; switching the interface language keeps the input.",
        "workflow_rule": "Independent rule baseline",
        "workflow_rule_help": "Find configured high-risk terms and claims that need evidence.",
        "workflow_retrieval": "Case retrieval",
        "workflow_retrieval_help": "Return the three closest texts from 30 case records.",
        "workflow_threshold": "Evidence threshold",
        "workflow_threshold_help": "Use the provisional 0.30 threshold to assess retrieval support.",
        "workflow_decision": "Model screening or human-review notice",
        "workflow_decision_help": "Call the model at most once at or above the threshold; otherwise abstain and ask the user to arrange human review.",
        "baseline_independent": "The rule result is an independent baseline and does not determine the final risk card.",
        "reference_rules_title": "Project reference labels",
        "reference_rules_help": "These three human-authored project labels support evaluation; they are not official labels issued by a regulator.",
        "empty_state_label": "Awaiting input",
        "empty_state_title": "The result will unfold here along the evidence trail",
        "empty_input_step": "Keep the original claim visible for later verification.",
        "empty_evidence_step": "Retrieve similar cases and check the provisional threshold.",
        "empty_review_step": "Return a risk signal, or ask the user to arrange human review when support is insufficient.",
        "empty_state_note": "Similarity measures text proximity only; it is not a probability of illegality.",
        "result_ready": "Preliminary result ready",
        "result_ready_help": "Reasoning, case sources and technical details are shown below.",
        "principle_score_title": "Similarity is not risk probability",
        "principle_score_body": "It only measures how closely the input resembles case text.",
        "principle_source_title": "Citations must support the conclusion",
        "principle_source_body": "Historical cases provide analogy, not proof of current facts.",
        "principle_human_title": "People own publication decisions",
        "principle_human_body": "No system output is an automatic approval.",
        "results_title": "Review result",
        "results_help": "See the outcome and action first, then verify how the evidence trail was formed.",
        "baseline_result": "Rule baseline",
        "independent_baseline": "Independent comparison only",
        "best_similarity": "Best case text similarity",
        "text_similarity_only": "Text similarity only",
        "final_risk": "Screening risk level",
        "human_review": "Human review required",
        "review_required": "No definite system judgement",
        "human_confirmation": "Human confirmation still required",
        "human_confirmation_required": "Human confirmation before publication",
        "automatic_judgment": "System judgement status",
        "auto_completed": "Completed",
        "auto_declined": "Declined",
        "yes": "Yes",
        "no": "No",
        "not_available": "Unavailable",
        "assessment_interrupted": "Case retrieval was not completed",
        "assessment_incomplete": "Assessment incomplete",
        "no_automatic_conclusion": "No automatic approval or risk conclusion",
        "tab_overview": "Overview",
        "tab_cases": "Similar cases",
        "tab_rules": "Rule details",
        "tab_evidence": "Evidence and rules",
        "tab_technical": "Technical details",
        "system_error": "The assessment could not be completed. Human review is needed; please arrange it yourself.",
        "system_error_action": "Do not publish based on this result; retry later or ask a person to review it.",
        "risk_level": "Screening risk level",
        "highlighted_claim": "Highlighted claim",
        "system_explanation": "System explanation",
        "model_original_reason": "Original model explanation",
        "next_action": "Recommended next step",
        "decision_label": "Preliminary screening outcome",
        "evidence_reason": "What was found",
        "evidence_action": "What to do next",
        "why_this_result": "Reasoning",
        "what_to_do_next": "Recommended action",
        "rule_findings": "Rule findings",
        "case_sources": "Similar cases and sources",
        "model_original_action": "Original model recommendation",
        "confidence": "Model-reported confidence",
        "confidence_note": "This value is not an illegality or enforcement probability.",
        "abstained": "Automatic judgement declined",
        "supporting_source": "Cited source",
        "open_cited_source": "Open cited official source",
        "none": "None",
        "fixed_human_notice": "A person remains responsible for the final publication decision.",
        "trace_title": "ClaimTrace evidence trail",
        "trace_help": "The rule baseline is a separate comparison; the main trail shows cases, the threshold and screening or a human-review notice.",
        "trace_baseline": "Independent comparison",
        "trace_cases": "Case retrieval",
        "trace_cases_detail": "Best text similarity {score}; this is not a risk probability.",
        "trace_threshold": "Threshold gate",
        "trace_threshold_pass": "{score} ≥ provisional threshold {threshold}; proceed to model assessment.",
        "trace_threshold_fail": "{score} < provisional threshold {threshold}; support is insufficient.",
        "trace_decision": "Screening and review notice",
        "trace_model": "The model is called at most once and returns a risk signal.",
        "trace_human": "The system declines a definite judgement. Human review is needed; please arrange it yourself.",
        "trace_error": "The flow did not complete. Human review is needed; no task has been dispatched. Please arrange review yourself.",
        "trace_unavailable": "No reportable data is available for this request.",
        "similarity_disclaimer": "These values are text similarity only. A similar historical case does not establish identical products, sellers or facts.",
        "language_content_note": "Model explanations and external case titles may remain in their original language; the interface does not claim that this content is fully translated.",
        "case_rank": "Similar case {index}",
        "case_id": "Case ID",
        "text_similarity": "Text similarity",
        "risk_type": "Recorded case risk type",
        "case_summary": "View case summary",
        "official_source": "Open official source",
        "no_cases_available": "No case result is available for this assessment.",
        "matched_fragment": "Matched source text",
        "rule_explanation": "Rule explanation",
        "no_rule_match": "No configured expression was matched by the limited rule set.",
        "no_rule_match_help": "This does not mean the claim is true, legal or approved. Confirm product facts and supporting records manually.",
        "rule_scope_note": "The rule list is not a complete legal rulebook; no match does not mean approval.",
        "technical_expander": "Expand technical details for this request",
        "threshold": "Provisional threshold",
        "llm_called": "Model called",
        "model": "Model name",
        "not_called": "Not called",
        "threshold_note": "0.30 is a provisional retrieval threshold and has not been fully calibrated.",
        "single_request_usage": "Usage reported for this request",
        "prompt_tokens": "Prompt tokens",
        "completion_tokens": "Completion tokens",
        "request_total_tokens": "Request total tokens",
        "request_cost": "Request cost",
        "usage_not_reported": "The service did not report token or cost data for this request.",
        "model_error_type": "Model or pipeline error type",
        "no_usage_on_error": "The assessment did not complete, so no model usage is reported.",
        "technical_boundary": "Technical values explain this request; they are not probabilities of illegality, enforcement or a legal conclusion.",
        "final_responsibility": "Low risk is not legal approval; final publication still requires human confirmation.",
        "sidebar_title": "Review workspace",
        "sidebar_status": "Prototype · single-claim screening",
        "sidebar_guide": "Status legend",
        "sidebar_limits": "Key boundaries",
        "rule_high_title": "High risk",
        "rule_high_body": "Cure guarantees such as 治愈, 根治 and 包治, plus high-risk superlatives such as 最佳, 最高级 and 国家级.",
        "rule_evidence_title": "Evidence needed",
        "rule_evidence_body": "Sales and rankings, price and plans, materials and origin, certificates, performance, effects, improvements or enhancement claims.",
        "rule_low_title": "Lower risk",
        "rule_low_body": "Only means no configured concern was found in the limited rules and case library; it is not truth, legality or approval.",
        "rule_insufficient_title": "Insufficient evidence",
        "rule_insufficient_body": "Not a reference label; the system declines a definite judgement when retrieval support is weak and requires human review.",
        "limit_rules": "The rule list is not a complete legal rulebook.",
        "limit_cases": "A similar historical case does not establish identical current facts.",
        "limit_citation": "A citation must genuinely support the current conclusion.",
        "limit_threshold": "The current 0.30 threshold is provisional.",
        "limit_human": "Final publication requires human confirmation.",
        "rule_medical": "The fragment contains a treatment or cure guarantee.",
        "rule_superlative": "The fragment contains a high-risk absolute or superlative expression.",
        "rule_sales": "A sales or ranking claim needs verifiable transaction records.",
        "rule_price": "A price or plan claim needs verification against the actual offer and conditions.",
        "rule_effect": "A product effect or improvement claim needs reliable supporting evidence.",
        "retrieval_below_threshold": "Retrieval evidence is below the provisional threshold, so the system did not assign a definite label.",
        "send_human_review": "Send this claim for human review before publication.",
    },
}


RISK_TEXT = {
    "high_risk": {
        "zh": {"name": "高风险", "icon": "!", "description": "应暂停发布并重点复核", "action": "暂停发布；修改高风险表达并进行人工复核。"},
        "en": {"name": "High risk", "icon": "!", "description": "Pause publication and review closely", "action": "Pause publication, revise the high-risk wording and obtain human review."},
    },
    "evidence_needed": {
        "zh": {"name": "需要证据", "icon": "◆", "description": "发布前需要可靠记录支持", "action": "核对产品、交易或供应商记录后再决定是否发布。"},
        "en": {"name": "Evidence needed", "icon": "◆", "description": "Reliable records are needed before publication", "action": "Verify product, transaction or supplier records before publication."},
    },
    "low_risk": {
        "zh": {"name": "未发现已配置的明显风险", "icon": "○", "description": "不等于法律批准，仍需人工确认", "action": "继续人工检查商品事实和平台要求后再发布。"},
        "en": {"name": "No configured concern identified", "icon": "○", "description": "Not legal approval; human confirmation is still required", "action": "Continue human checks of product facts and platform requirements."},
    },
    "insufficient_evidence": {
        "zh": {"name": "证据不足，转人工", "icon": "→", "description": "检索证据不足，系统拒绝给出确定标签", "action": "发布前交由人工复核，不要把转人工理解为低风险。"},
        "en": {"name": "Insufficient evidence — human review required", "icon": "→", "description": "Retrieval support is insufficient for a definite label", "action": "Obtain human review before publication; abstention is not low risk."},
    },
}


def t(key: str, lang: str = "zh", **values: object) -> str:
    """Return one localised UI string and interpolate named values."""
    language = lang if lang in UI_TEXT else "zh"
    text = UI_TEXT[language].get(key, UI_TEXT["zh"].get(key, key))
    return text.format(**values) if values else text
