"""Centralised bilingual copy for the ClaimTrace Streamlit interface."""


UI_TEXT = {
    "zh": {
        "page_subtitle": "中文电商广告宣称风险初筛",
        "page_eyebrow": "E-COMMERCE COPY RISK SCREENING",
        "english_subtitle": "Evidence-grounded screening for Chinese e-commerce advertising claims",
        "language_label": "界面语言",
        "boundary_title": "发布前初筛，而非自动审批",
        "boundary_text": "本工具仅提供发布前的初步风险筛查，不构成法律意见，也不会自动批准商品文案。正式发布仍需人工确认。",
        "start_review": "开始审查",
        "start_review_help": "一次输入一条中文商品文案，查看规则、案例与风险提示。",
        "claim_label": "待审查的中文商品文案",
        "claim_placeholder": "例如：本产品是全网销量第一的护肤品。",
        "character_count": "当前 {count} 个字符",
        "try_example": "使用示例",
        "example_high": "高风险示例",
        "example_evidence": "需要证据示例",
        "example_low": "较低风险示例",
        "example_high_text": "这款普通靠垫保证彻底治愈腰椎间盘突出。",
        "example_evidence_text": "每月只花9元，就能不限量使用全部高速流量。",
        "example_low_text": "这款笔记本可选择横线页或空白页。",
        "clear": "清空文案",
        "assess_claim": "开始风险审查",
        "empty_input": "请先输入一条中文商品文案；系统尚未运行。",
        "assessing": "正在检索案例并准备风险评估……",
        "workflow_title": "系统如何处理",
        "workflow_help": "四个步骤共同提供可追溯的初筛结果。",
        "workflow_rule": "规则初筛",
        "workflow_rule_help": "识别已配置的高风险词与需要证明的宣称。",
        "workflow_retrieval": "案例检索",
        "workflow_retrieval_help": "从 30 条案例记录中返回文本最相近的 3 条。",
        "workflow_threshold": "证据阈值",
        "workflow_threshold_help": "以暂定阈值 0.30 判断是否有足够检索证据。",
        "workflow_decision": "模型评估或转人工",
        "workflow_decision_help": "达到阈值时至多调用模型一次，否则直接转人工。",
        "baseline_independent": "规则结果是独立基线，不直接决定最终风险卡。",
        "results_title": "审查结果",
        "results_help": "先看结论与行动，再按需展开案例、规则和技术信息。",
        "baseline_result": "规则初筛结果",
        "independent_baseline": "独立基线，仅作对照",
        "best_similarity": "最佳案例文本相似度",
        "text_similarity_only": "仅表示文本相似程度",
        "final_risk": "最终风险等级",
        "human_review": "是否需要转人工",
        "review_required": "系统未给出确定判断",
        "human_confirmation": "发布前仍需人工确认",
        "yes": "是",
        "no": "否",
        "not_available": "不可用",
        "assessment_interrupted": "系统未完成案例检索",
        "assessment_incomplete": "评估未完成",
        "no_automatic_conclusion": "不输出自动批准或风险结论",
        "tab_overview": "结果概览",
        "tab_cases": "相似案例",
        "tab_rules": "规则详情",
        "tab_technical": "技术信息",
        "system_error": "系统未能完成本次评估，已转交人工复核。",
        "system_error_action": "请勿据此发布文案；可稍后重试或交由人工检查。",
        "risk_level": "风险等级",
        "highlighted_claim": "重点文案",
        "system_explanation": "系统说明",
        "model_original_reason": "模型原始解释",
        "next_action": "建议的下一步",
        "model_original_action": "模型原始建议",
        "confidence": "模型自报置信值",
        "confidence_note": "该值不是违法概率或监管处罚概率。",
        "abstained": "是否拒绝自动判断",
        "supporting_source": "引用来源",
        "open_cited_source": "打开引用的官方来源",
        "none": "无",
        "fixed_human_notice": "正式发布决定始终由人工负责。",
        "similarity_disclaimer": "以下数值仅为文本相似度。历史案例相似不等于当前商品、商家或事实相同。",
        "case_rank": "相似案例 {index}",
        "case_id": "案例编号",
        "text_similarity": "文本相似度",
        "risk_type": "案例记录的风险类型",
        "case_summary": "查看案例摘要",
        "official_source": "打开官方来源",
        "no_cases_available": "本次评估没有可显示的案例结果。",
        "matched_fragment": "命中的原文片段",
        "rule_explanation": "对应规则说明",
        "no_rule_match": "有限规则库未命中已配置的表达。",
        "no_rule_match_help": "这不代表文案真实、合法或获得批准，仍需结合商品事实和证明材料人工确认。",
        "rule_scope_note": "规则列表不是完整法律规则库，未命中不等于批准。",
        "technical_expander": "展开本次请求的技术信息",
        "threshold": "暂定阈值",
        "llm_called": "是否调用模型",
        "model": "模型名称",
        "not_called": "未调用",
        "threshold_note": "0.30 为暂定检索阈值，尚未经过充分校准。",
        "single_request_usage": "服务返回的单次请求用量",
        "prompt_tokens": "输入 Token",
        "completion_tokens": "输出 Token",
        "request_total_tokens": "本次总 Token",
        "request_cost": "本次请求成本",
        "usage_not_reported": "服务未返回本次请求的 Token 或成本数据。",
        "model_error_type": "模型或流程错误类型",
        "no_usage_on_error": "评估未完成，因此没有可报告的模型用量。",
        "final_responsibility": "低风险不等于法律批准；正式发布仍需人工确认。",
        "sidebar_title": "审查工作台",
        "sidebar_status": "原型系统 · 单条文案初筛",
        "sidebar_guide": "规则与标签说明",
        "sidebar_limits": "必须了解的边界",
        "rule_high_title": "高风险",
        "rule_high_body": "治愈、根治、包治等治疗保证，以及最佳、最高级、国家级等高风险绝对化表达。",
        "rule_evidence_title": "需要证据",
        "rule_evidence_body": "销量与排名、价格与套餐、材质与来源、证书、性能、效果、改善或提升等宣称。",
        "rule_low_title": "较低风险",
        "rule_low_body": "仅表示有限规则和案例库中未识别出明显风险；不代表真实、合法或获批。",
        "rule_insufficient_title": "证据不足",
        "rule_insufficient_body": "不是参考标签；表示系统拒绝在检索证据不足时给出确定判断，应转人工。",
        "limit_rules": "规则列表不是完整法律规则库。",
        "limit_cases": "历史案例相似不等于当前事实相同。",
        "limit_citation": "引用必须真正支持当前结论。",
        "limit_threshold": "当前阈值 0.30 只是暂定值。",
        "limit_human": "正式发布需要人工确认。",
        "rule_medical": "该片段包含疾病治疗或治愈保证。",
        "rule_superlative": "该片段包含高风险绝对化或最高级表达。",
        "rule_sales": "销量或排名宣称需要可核验的交易记录支持。",
        "rule_price": "价格或套餐宣称需要与实际优惠和条件核对。",
        "rule_effect": "产品效果或改善宣称需要可靠证明材料支持。",
        "retrieval_below_threshold": "检索证据低于暂定阈值，系统未给出确定标签。",
        "send_human_review": "发布前请将该文案交由人工复核。",
    },
    "en": {
        "page_subtitle": "Risk screening for Chinese e-commerce advertising claims",
        "page_eyebrow": "E-COMMERCE COPY RISK SCREENING",
        "english_subtitle": "Evidence-grounded screening for Chinese e-commerce advertising claims",
        "language_label": "Interface language",
        "boundary_title": "Pre-publication screening, not automatic approval",
        "boundary_text": "This tool provides preliminary pre-publication screening only. It does not provide legal advice or automatically approve product copy. Final publication requires human confirmation.",
        "start_review": "Start a review",
        "start_review_help": "Enter one Chinese product claim to inspect rules, cases and risk signals.",
        "claim_label": "Chinese product claim to review",
        "claim_placeholder": "For example: 本产品是全网销量第一的护肤品。",
        "character_count": "{count} characters",
        "try_example": "Try an example",
        "example_high": "High-risk example",
        "example_evidence": "Evidence example",
        "example_low": "Lower-risk example",
        "example_high_text": "这款普通靠垫保证彻底治愈腰椎间盘突出。",
        "example_evidence_text": "每月只花9元，就能不限量使用全部高速流量。",
        "example_low_text": "这款笔记本可选择横线页或空白页。",
        "clear": "Clear claim",
        "assess_claim": "Start risk review",
        "empty_input": "Enter a Chinese product claim first; the system has not run.",
        "assessing": "Retrieving cases and preparing the assessment…",
        "workflow_title": "How the system works",
        "workflow_help": "Four steps provide a traceable preliminary screen.",
        "workflow_rule": "Rule screening",
        "workflow_rule_help": "Find configured high-risk terms and claims that need evidence.",
        "workflow_retrieval": "Case retrieval",
        "workflow_retrieval_help": "Return the three closest texts from 30 case records.",
        "workflow_threshold": "Evidence threshold",
        "workflow_threshold_help": "Use the provisional 0.30 threshold to assess retrieval support.",
        "workflow_decision": "Model assessment or human review",
        "workflow_decision_help": "Call the model at most once above the threshold; otherwise abstain.",
        "baseline_independent": "The rule result is an independent baseline and does not determine the final risk card.",
        "results_title": "Review result",
        "results_help": "See the outcome and action first, then inspect cases, rules and technical details.",
        "baseline_result": "Rule baseline",
        "independent_baseline": "Independent comparison only",
        "best_similarity": "Best case text similarity",
        "text_similarity_only": "Text similarity only",
        "final_risk": "Final risk level",
        "human_review": "Human review required",
        "review_required": "No definite system judgement",
        "human_confirmation": "Human confirmation still required",
        "yes": "Yes",
        "no": "No",
        "not_available": "Unavailable",
        "assessment_interrupted": "Case retrieval was not completed",
        "assessment_incomplete": "Assessment incomplete",
        "no_automatic_conclusion": "No automatic approval or risk conclusion",
        "tab_overview": "Overview",
        "tab_cases": "Similar cases",
        "tab_rules": "Rule details",
        "tab_technical": "Technical details",
        "system_error": "The assessment could not be completed and requires human review.",
        "system_error_action": "Do not publish based on this result; retry later or ask a person to review it.",
        "risk_level": "Risk level",
        "highlighted_claim": "Highlighted claim",
        "system_explanation": "System explanation",
        "model_original_reason": "Original model explanation",
        "next_action": "Recommended next step",
        "model_original_action": "Original model recommendation",
        "confidence": "Model-reported confidence",
        "confidence_note": "This value is not an illegality or enforcement probability.",
        "abstained": "Automatic judgement declined",
        "supporting_source": "Cited source",
        "open_cited_source": "Open cited official source",
        "none": "None",
        "fixed_human_notice": "A person remains responsible for the final publication decision.",
        "similarity_disclaimer": "These values are text similarity only. A similar historical case does not establish identical products, sellers or facts.",
        "case_rank": "Similar case {index}",
        "case_id": "Case ID",
        "text_similarity": "Text similarity",
        "risk_type": "Recorded case risk type",
        "case_summary": "View case summary",
        "official_source": "Open official source",
        "no_cases_available": "No case result is available for this assessment.",
        "matched_fragment": "Matched source text",
        "rule_explanation": "Rule explanation",
        "no_rule_match": "No configured expression was matched by the limited rule set.",
        "no_rule_match_help": "This does not mean the claim is true, legal or approved. Confirm product facts and supporting records manually.",
        "rule_scope_note": "The rule list is not a complete legal rulebook; no match does not mean approval.",
        "technical_expander": "Expand technical details for this request",
        "threshold": "Provisional threshold",
        "llm_called": "Model called",
        "model": "Model name",
        "not_called": "Not called",
        "threshold_note": "0.30 is a provisional retrieval threshold and has not been fully calibrated.",
        "single_request_usage": "Usage reported for this request",
        "prompt_tokens": "Prompt tokens",
        "completion_tokens": "Completion tokens",
        "request_total_tokens": "Request total tokens",
        "request_cost": "Request cost",
        "usage_not_reported": "The service did not report token or cost data for this request.",
        "model_error_type": "Model or pipeline error type",
        "no_usage_on_error": "The assessment did not complete, so no model usage is reported.",
        "final_responsibility": "Low risk is not legal approval; final publication still requires human confirmation.",
        "sidebar_title": "Review workspace",
        "sidebar_status": "Prototype · single-claim screening",
        "sidebar_guide": "Rules and labels",
        "sidebar_limits": "Important boundaries",
        "rule_high_title": "High risk",
        "rule_high_body": "Cure guarantees such as 治愈, 根治 and 包治, plus high-risk superlatives such as 最佳, 最高级 and 国家级.",
        "rule_evidence_title": "Evidence needed",
        "rule_evidence_body": "Sales and rankings, price and plans, materials and origin, certificates, performance, effects, improvements or enhancement claims.",
        "rule_low_title": "Lower risk",
        "rule_low_body": "Only means no configured concern was found in the limited rules and case library; it is not truth, legality or approval.",
        "rule_insufficient_title": "Insufficient evidence",
        "rule_insufficient_body": "Not a reference label; the system declines a definite judgement when retrieval support is weak and sends it to human review.",
        "limit_rules": "The rule list is not a complete legal rulebook.",
        "limit_cases": "A similar historical case does not establish identical current facts.",
        "limit_citation": "A citation must genuinely support the current conclusion.",
        "limit_threshold": "The current 0.30 threshold is provisional.",
        "limit_human": "Final publication requires human confirmation.",
        "rule_medical": "The fragment contains a treatment or cure guarantee.",
        "rule_superlative": "The fragment contains a high-risk absolute or superlative expression.",
        "rule_sales": "A sales or ranking claim needs verifiable transaction records.",
        "rule_price": "A price or plan claim needs verification against the actual offer and conditions.",
        "rule_effect": "A product effect or improvement claim needs reliable supporting evidence.",
        "retrieval_below_threshold": "Retrieval evidence is below the provisional threshold, so the system did not assign a definite label.",
        "send_human_review": "Send this claim for human review before publication.",
    },
}


RISK_TEXT = {
    "high_risk": {
        "zh": {"name": "高风险", "icon": "!", "description": "应暂停发布并重点复核", "action": "暂停发布；修改高风险表达并进行人工复核。"},
        "en": {"name": "High risk", "icon": "!", "description": "Pause publication and review closely", "action": "Pause publication, revise the high-risk wording and obtain human review."},
    },
    "evidence_needed": {
        "zh": {"name": "需要证据", "icon": "◆", "description": "发布前需要可靠记录支持", "action": "核对产品、交易或供应商记录后再决定是否发布。"},
        "en": {"name": "Evidence needed", "icon": "◆", "description": "Reliable records are needed before publication", "action": "Verify product, transaction or supplier records before publication."},
    },
    "low_risk": {
        "zh": {"name": "未发现已配置的明显风险", "icon": "✓", "description": "不等于法律批准，仍需人工确认", "action": "继续人工检查商品事实和平台要求后再发布。"},
        "en": {"name": "No configured concern identified", "icon": "✓", "description": "Not legal approval; human confirmation is still required", "action": "Continue human checks of product facts and platform requirements."},
    },
    "insufficient_evidence": {
        "zh": {"name": "证据不足，转人工", "icon": "→", "description": "检索证据不足，系统拒绝给出确定标签", "action": "发布前交由人工复核，不要把转人工理解为低风险。"},
        "en": {"name": "Insufficient evidence — human review required", "icon": "→", "description": "Retrieval support is insufficient for a definite label", "action": "Obtain human review before publication; abstention is not low risk."},
    },
}


def t(key: str, lang: str = "zh", **values: object) -> str:
    """Return one localised UI string and interpolate named values."""
    language = lang if lang in UI_TEXT else "zh"
    text = UI_TEXT[language].get(key, UI_TEXT["zh"].get(key, key))
    return text.format(**values) if values else text
